### ISSUE TITLE
Option to disable the 'Scanning Unavailable' dialog in iOS

### ISSUE THREAD

**Issue by viplavrawal** [juliuscanute/qr_code_scanner#103]
We are building a multilingual application and would like a way to disable the 'Scanning Unavailable' dialog from the plugin, so that we can implement it on our end.

**Comment by micaelsn** [comment]
same here

**Comment by juliansteenbakker** [comment]
With version 0.3.0, this dialog is replaced with a PlatformException. You can catch this error and provide your own dialog.
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(cameraPermission, Permission denied to access the camera, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
```
