### ISSUE TITLE
Is there any way to identify that camera permission set to never ask again?

### ISSUE THREAD

**Issue by DhavalRKansara** [juliuscanute/qr_code_scanner#121]
Using this plugin is there any way to identify that the user has **denied camera permission with never ask again**?

I have run the example of this plugin in my android phone and when App asks me for camera permission I denied with never ask again and next time I open the app it shows me a black screen with below error logs.

So is there any way using which I catch this type of camera permission exception in my code so we can guide a user to go to setting and turn of the permission?

```
scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
D/Camera-JNI(20612): android_hardware_Camera_native_setup after halVersion -2
W/CameraBase(20612): An error occurred while connecting to camera 0: Status(-8): '1: validateClientPermissionsLocked:1149: Caller "net.touchcapture.qr.flutterqrexample" (PID 10441, UID 20612) cannot open camera "0" without camera permission'
E/CameraInstance(20612): Failed to open camera
E/CameraInstance(20612): java.lang.RuntimeException: Fail to connect to camera service
E/CameraInstance(20612): 	at android.hardware.Camera.<init>(Camera.java:847)
E/CameraInstance(20612): 	at android.hardware.Camera.open(Camera.java:494)
E/CameraInstance(20612): 	at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
E/CameraInstance(20612): 	at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:142)
E/CameraInstance(20612): 	at com.journeyapps.barcodescanner.camera.CameraInstance$1.run(CameraInstance.java:200)
E/CameraInstance(20612): 	at android.os.Handler.handleCallback(Handler.java:873)
E/CameraInstance(20612): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraInstance(20612): 	at android.os.Looper.loop(Looper.java:224)
E/CameraInstance(20612): 	at android.os.HandlerThread.run(HandlerThread.java:65)
D/OrientationEventListener(20612): Orientation is:4 X:0.4934082 Y:-6.4414825 Z:-7.5184937
D/CameraInstance(20612): Configuring camera
E/CameraInstance(20612): Failed to configure camera
E/CameraInstance(20612): java.lang.RuntimeException: Camera not open
E/CameraInstance(20612): 	at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:161)
E/CameraInstance(20612): 	at com.journeyapps.barcodescanner.camera.CameraInstance$2.run(CameraInstance.java:213)
E/CameraInstance(20612): 	at android.os.Handler.handleCallback(Handler.java:873)
E/CameraInstance(20612): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraInstance(20612): 	at android.os.Looper.loop(Looper.java:224)
E/CameraInstance(20612): 	at android.os.HandlerThread.run(HandlerThread.java:65)
D/CameraPreview(20612): pause()
D/CameraInstance(20612): Closing camera

```

**Comment by dspicher** [comment]
You can wrap Scanner usage with a widget that uses [`permission_handler`](https://pub.dev/packages/permission_handler). Then you can check for `permanentlyDenied`.

Closing this for now, feel free to reopen if you think this issue still applies to this library.
