### ISSUE TITLE
PlatformException: Trying to create a platform view of unregistered type

### ISSUE THREAD

**Issue by TiffaaMC** [juliuscanute/qr_code_scanner#162]
Hello,

I tried the example on the pub.dev page, with minSDK = 24, and tested it on my physical POCO F1 (AOS 10) :
If I resume the app debug after this error, it continues to run and displays the QR scan page, but black camera and the widget buttons don't do anything (flash, resume, pause, etc).

I also tested it on my emulator with the same phone model (API 29), and it works fine.

Any idea on what could be the issue ? Please let me know if I need to add anything to this issue that could help, it is actually my first time reporting an issue on Github and I don't know the usual stuff to include :sweat_smile: 

Logs of the error:

```
[+14146 ms] E/flutter (32635): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: net.touchcapture.qr.flutterqr/qrview
[        ] E/flutter (32635): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:199)
[        ] E/flutter (32635): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
[        ] E/flutter (32635): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
[        ] E/flutter (32635): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
[        ] E/flutter (32635): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[   +3 ms] E/flutter (32635): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
[        ] E/flutter (32635): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/flutter (32635): 	at android.os.MessageQueue.next(MessageQueue.java:336)
[   +1 ms] E/flutter (32635): 	at android.os.Looper.loop(Looper.java:181)
[        ] E/flutter (32635): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
[        ] E/flutter (32635): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/flutter (32635): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[        ] E/flutter (32635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[        ] E/flutter (32635): , null, null)
[  +10 ms] E/flutter (32635): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
[   +1 ms] E/flutter (32635): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
[   +1 ms] E/flutter (32635): <asynchronous suspension>
[   +6 ms] E/flutter (32635): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
[   +1 ms] E/flutter (32635): #3      TextureAndroidViewController._sendCreateMessage
package:flutter/…/services/platform_views.dart:1038
[        ] E/flutter (32635): #4      AndroidViewController.create
package:flutter/…/services/platform_views.dart:748
[   +9 ms] E/flutter (32635): #5      TextureAndroidViewController.create
[   +6 ms] E/flutter (32635): #6      TextureAndroidViewController.setSize
package:flutter/…/services/platform_views.dart:1001
[        ] E/flutter (32635): #7      RenderAndroidView._sizePlatformView
package:flutter/…/rendering/platform_view.dart:190
[        ] E/flutter (32635): #8      RenderAndroidView.performResize
package:flutter/…/rendering/platform_view.dart:171
[        ] E/flutter (32635): #9      RenderObject.layout
package:flutter/…/rendering/object.dart:1756
[        ] E/flutter (32635): #10     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:111
[        ] E/flutter (32635): #11     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #12     RenderStack.performLayout
package:flutter/…/rendering/stack.dart:564
[        ] E/flutter (32635): #13     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #14     RenderFlex.performLayout
package:flutter/…/rendering/flex.dart:830
[        ] E/flutter (32635): #15     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #16     MultiChildLayoutDelegate.layoutChild
package:flutter/…/rendering/custom_layout.dart:171
[        ] E/flutter (32635): #17     _ScaffoldLayout.performLayout
package:flutter/…/material/scaffold.dart:498
[        ] E/flutter (32635): #18     MultiChildLayoutDelegate._callPerformLayout
package:flutter/…/rendering/custom_layout.dart:243
[        ] E/flutter (32635): #19     RenderCustomMultiChildLayoutBox.performLayout
package:flutter/…/rendering/custom_layout.dart:402
[        ] E/flutter (32635): #20     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #21     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:111
[        ] E/flutter (32635): #22     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #23     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:111
[   +1 ms] E/flutter (32635): #24     _RenderCustomClip.performLayout
package:flutter/…/rendering/proxy_box.dart:1306
[        ] E/flutter (32635): #25     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #26     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:111
[        ] E/flutter (32635): #27     RenderObject.layout
package:flutter/…/rendering/object.dart:1777
[        ] E/flutter (32635): #28     RenderProxyBoxMixin.performLayout
package:flutter/…/rendering/proxy_box.dart:111
[        ] E/flutter (32635): #29     RenderObject.layout (package:flutter/src/rende

════════ Exception caught by widgets library ═══════════════════════════════════
The method 'dispose' was called on null.
Receiver: null
Tried calling: dispose()
════════════════════════════════════════════════════════════════════════════════
```

**Comment by TiffaaMC** [comment]
Restarted my PC, and my phone, and it worked somehow...
I guess I was too hasty.
