### ISSUE TITLE
[BUG] When QR scanner screen is loaded, I am getting NullPointerException.

### ISSUE THREAD

**Issue by Rakesh-Card91** [juliuscanute/qr_code_scanner#181]
**Describe the bug**
When QR scanner screen is loaded, I am getting NullPointerException. Attaching logcat for reference .

```
E/MethodChannel#flutter/platform_views(19919): Failed to handle method call
E/MethodChannel#flutter/platform_views(19919): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
E/MethodChannel#flutter/platform_views(19919): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.View.<init>(View.java:4006)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.View.<init>(View.java:4126)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:578)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:574)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:570)
E/MethodChannel#flutter/platform_views(19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:566)
E/MethodChannel#flutter/platform_views(19919): 	at com.journeyapps.barcodescanner.CameraPreview.<init>(CameraPreview.java:228)
E/MethodChannel#flutter/platform_views(19919): 	at com.journeyapps.barcodescanner.BarcodeView.<init>(BarcodeView.java:76)
E/MethodChannel#flutter/platform_views(19919): 	at net.touchcapture.qr.flutterqr.QRView.createBarCodeView(QRView.kt:115)
E/MethodChannel#flutter/platform_views(19919): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView.kt:109)
E/MethodChannel#flutter/platform_views(19919): 	at net.touchcapture.qr.flutterqr.QRView.getView(QRView.kt:102)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:189)
E/MethodChannel#flutter/platform_views(19919): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:389)
E/MethodChannel#flutter/platform_views(19919): 	at android.app.Dialog.show(Dialog.java:293)
E/MethodChannel#flutter/platform_views(19919): 	at android.app.Presentation.show(Presentation.java:235)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(19919): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:693)
E/MethodChannel#flutter/platform_views(19919): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(19919): 	at android.os.MessageQueue.next(MessageQueue.java:329)
E/MethodChannel#flutter/platform_views(19919): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter/platform_views(19919): 	at android.app.ActivityThread.main(ActivityThread.java:6375)
E/MethodChannel#flutter/platform_views(19919): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(19919): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
E/MethodChannel#flutter/platform_views(19919): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
I/flutter (19919): runZonedGuarded: Caught error in my root zone.
I/flutter (19919): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (19919): PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
I/flutter (19919): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:364)
I/flutter (19919): 	at android.view.View.<init>(View.java:4006)
I/flutter (19919): 	at android.view.View.<init>(View.java:4126)
I/flutter (19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:578)
I/flutter (19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:574)
I/flutter (19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:570)
I/flutter (19919): 	at android.view.ViewGroup.<init>(ViewGroup.java:566)
I/flutter (19919): 	at com.journeyapps.barcodescanner.CameraPreview.<init>(CameraPreview.java:228)
I/flutter (19919): 	at com.journeyapps.barcodescanner.BarcodeView.<init>(BarcodeView.java:76)
I/flutter (19919): 	at net.touchcapture.qr.flutterqr.QRView.createBarCodeView(QRView.kt:115)
I/flutter (19919): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView.kt:109)
I/flutter (19919): 	at net.touchcapture.qr
I/flutter (19919): 
I/flutter (19919): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (19919): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (19919): <asynchronous suspension>
I/flutter (19919): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1037:18)
I/flutter (19919): <asynchronous suspension>
I/flutter (19919): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:743:5)
I/flutter (19919): <asynchronous suspension>
I/flutter (19919): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:190:7)
I/flutter (19919): <asynchronous suspension>
I/flutter (19919): ----------------------------------------------------
```

**Flutter information**
```
[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IN)
    • Flutter version 1.24.0-10.2.pre at /Users/rakeshr/StudioProjects/flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rakeshr/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 12.2, Build version 12B5044c
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Redmi Note 4 (mobile) • eeedd8bd0603 • android-arm64 • Android 7.0 (API 24)

```
**Device (please complete the following information):**
 - Device: Redmi Note 4
 - OS: Android 7.0

**Screenshots**
![Screenshot_2020-12-17-11-17-41-175_com card91 customer android](https://user-images.githubusercontent.com/73934710/102449233-d2edd100-4059-11eb-9bd8-5c44c9e13826.jpg)

**Comment by juliansteenbakker** [comment]
Can you switch your flutter to stable channel by running `flutter channel stable` and after that `flutter upgrade` and try again?

**Comment by Rakesh-Card91** [comment]
> Can you switch your flutter to stable channel by running `flutter channel stable` and after that `flutter upgrade` and try again?

Followed the steps, but results seems to be the same.

**Comment by juliansteenbakker** [comment]
Are you using the latest 0.1.0 version? I think it has to do with the plugin registering after the activity has started. I'll try to write a fix.

**Comment by Rakesh-Card91** [comment]
> Are you using the latest 0.1.0 version? I think it has to do with the plugin registering after the activity has started. I'll try to write a fix.

Yes, using the latest one **0.1.0**

**Comment by juliansteenbakker** [comment]
I have made an update in branch 181-nullpointer. can you check if this resolves your problem? You can use the branch in your pubspec.yaml as follows:

```
  qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner
      ref: 181-nullpointer
```

Be aware that there are some other breaking changes in this branch aswel. Most notably the plugin is not returing a String but rather a barcode object which also contains barcode type. Check the readme.md for clarification.

**Comment by Rakesh-Card91** [comment]
> I have made an update in branch 181-nullpointer. can you check if this resolves your problem? You can use the branch in your pubspec.yaml as follows:
> 
> ```
>   qr_code_scanner:
>     git:
>       url: git://github.com/juliuscanute/qr_code_scanner
>       ref: 181-nullpointer
> ```
> 
> Be aware that there are some other breaking changes in this branch aswel. Most notably the plugin is not returing a String but rather a barcode object which also contains barcode type. Check the readme.md for clarification.

Working

**Comment by mrfatbeard** [comment]
getting the same error in 0.6.1

`PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.view.ViewConfiguration.get(ViewConfiguration.java:476)
	at android.view.View.<init>(View.java:5198)
	at android.view.View.<init>(View.java:5393)
	at android.view.ViewGroup.<init>(ViewGroup.java:660)
	at android.view.ViewGroup.<init>(ViewGroup.java:656)
	at android.view.ViewGroup.<init>(ViewGroup.java:652)
	at android.view.ViewGroup.<init>(ViewGroup.java:648)
	at com.journeyapps.barcodescanner.CameraPreview.<init>(SourceFile:1)
	at com.journeyapps.barcodescanner.BarcodeView.<init>(SourceFile:1)
	at net.touchcapture.qr.flutterqr.CustomFramingRectBarcodeView.<init>(SourceFile:1)
	at net.touchcapture.qr.flutterqr.QRView.getView(SourceFile:4)
	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SourceFile:25)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:550)
	at android.app.Dialog.show(Dialog.java:391)
	at android.app.Presentation.show(Presentation.java:267)
	at io.flutter.plugin.platform.VirtualDisplayController.<init>(SourceFile:11)
	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(SourceFile:28)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(SourceFile:102)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(SourceFile:4)
	at w.a.a.b.b.a.run(SourceFile:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
)
`

**Device**
Samsung Galaxy Note 8, Android 9

**Flutter doctor**
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)

**Comment by RUSSCITY** [comment]
Same here:

```
E/MethodChannel#flutter/platform_views(10051): Failed to handle method call
E/MethodChannel#flutter/platform_views(10051): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
E/MethodChannel#flutter/platform_views(10051): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:545)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.View.<init>(View.java:5353)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.View.<init>(View.java:5513)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.ViewGroup.<init>(ViewGroup.java:747)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.ViewGroup.<init>(ViewGroup.java:743)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.ViewGroup.<init>(ViewGroup.java:739)
E/MethodChannel#flutter/platform_views(10051): 	at android.view.ViewGroup.<init>(ViewGroup.java:735)
E/MethodChannel#flutter/platform_views(10051): 	at com.journeyapps.barcodescanner.CameraPreview.<init>(CameraPreview.java:228)
E/MethodChannel#flutter/platform_views(10051): 	at com.journeyapps.barcodescanner.BarcodeView.<init>(BarcodeView.java:76)
E/MethodChannel#flutter/platform_views(10051): 	at net.touchcapture.qr.flutterqr.CustomFramingRectBarcodeView.<init>(CustomFramingRectBarcodeView.kt:12)
E/MethodChannel#flutter/platform_views(10051): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView.kt:117)
E/MethodChannel#flutter/platform_views(10051): 	at net.touchcapture.qr.flutterqr.QRView.getView(QRView.kt:70)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:227)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views(10051): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views(10051): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views(10051): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views(10051): 	at android.os.Looper.loopOnce(Looper.java:233)
E/MethodChannel#flutter/platform_views(10051): 	at android.os.Looper.loop(Looper.java:334)
E/MethodChannel#flutter/platform_views(10051): 	at android.app.ActivityThread.main(ActivityThread.java:8396)
E/MethodChannel#flutter/platform_views(10051): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(10051): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
E/MethodChannel#flutter/platform_views(10051): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

```

**Device**
Vivo Y20s (V2027). Android 12

**Flutter doctor**
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.22000.739], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)
[√] Android Studio (version 2021.1)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] VS Code (version 1.62.3)
[√] Connected device (5 available)
[√] HTTP Host Availability
