### ISSUE TITLE
[BUG] App crashing with infinite loop autoFocus failed

### ISSUE THREAD

**Issue by Jojoooo1** [juliuscanute/qr_code_scanner#233]
**Describe the bug**
When leaving widget page and re entering widget page app is crashing with with infinit loop
```
W/AutoFocusManager(28196): Unexpected exception while focusing
W/AutoFocusManager(28196): java.lang.RuntimeException: autoFocus failed
W/AutoFocusManager(28196): 	at android.hardware.Camera.native_autoFocus(Native Method)
W/AutoFocusManager(28196): 	at android.hardware.Camera.autoFocus(Camera.java:1602)
W/AutoFocusManager(28196): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.focus(AutoFocusManager.java:101)
W/AutoFocusManager(28196): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.access$100(AutoFocusManager.java:31)
W/AutoFocusManager(28196): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager$1.handleMessage(AutoFocusManager.java:57)
W/AutoFocusManager(28196): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/AutoFocusManager(28196): 	at android.os.Looper.loop(Looper.java:214)
W/AutoFocusManager(28196): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Flutter information**
```
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.5 at /mnt/sdb/Android/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /mnt/sdb/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /mnt/sdb/Android/Sdk
    • ANDROID_SDK_ROOT = /mnt/sdb/Android/Sdk
    • Java binary at: /mnt/sdb/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /mnt/sdb/Android/android-studio
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.52.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • GM1913 (mobile) • 192.168.0.2:5555 • android-arm64 • Android 10 (API 29)
```

**Device (please complete the following information):**
 - Device: OnePlus7
 - OS: Oxygen OS 10.0.10.GM21BA

**Screenshots**
![infinit-loop](https://user-images.githubusercontent.com/17641873/105481812-536da600-5c86-11eb-832b-c6a6814cdb9f.png)

**Comment by SooHoon95** [comment]
did you solve the problem? I still find the way of the same bug
