### ISSUE TITLE
[BUG] QRView freezes on navigating back

### ISSUE THREAD

**Issue by ChristianNavolskyi** [juliuscanute/qr_code_scanner#243]
**Describe the bug**
I have two routes both with a QRView. When I navigate from the first one to the other one the QRView works as expected, showing the camera feed. But when I navigate back to the first screen the QRView shows only a frozen image.

**Flutter information**
```
[✓] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19042.746], locale en-DE)
    • Flutter version 1.22.6 at C:\tools\flutter
    • Framework revision 9b2d32b605 (12 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\AndroidSdks
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\AndroidSdks
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Christian arconsis\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0
```
Please ignore the messages about the absent plugins and the license, they are all present and set, but somehow `flutter doctor` won't recognize.

**Device (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 11

**Screenshots**
Difficult to show the difference between a working and a not working camera feed in a screenshot...

**Additional context**
Here is the logging output from starting the app, navigating to the second screen and back to first screen again.
The example can be found [here](https://github.com/ChristianNavolskyi/qr_code_issue).

```
I/flutter (31322): Build first screen
D/CameraPreview(31322): resume()
D/CameraInstance(31322): Opening camera
W/CameraBase(31322): An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '1: validateClientPermissionsLocked:1165: Caller "com.example.qr_code_issue" (PID 10381, UID 31322) cannot open camera "0" without camera permission'
E/CameraInstance(31322): Failed to open camera
E/CameraInstance(31322): java.lang.RuntimeException: Fail to connect to camera service
E/CameraInstance(31322): 	at android.hardware.Camera.<init>(Camera.java:557)
E/CameraInstance(31322): 	at android.hardware.Camera.open(Camera.java:402)
E/CameraInstance(31322): 	at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
E/CameraInstance(31322): 	at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:142)
E/CameraInstance(31322): 	at com.journeyapps.barcodescanner.camera.CameraInstance$1.run(CameraInstance.java:200)
E/CameraInstance(31322): 	at android.os.Handler.handleCallback(Handler.java:938)
E/CameraInstance(31322): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraInstance(31322): 	at android.os.Looper.loop(Looper.java:223)
E/CameraInstance(31322): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/CameraPreview(31322): resume()
W/CameraPreview(31322): initCamera called twice
D/CameraPreview(31322): pause()
D/CameraInstance(31322): Closing camera
I/flutter (31322): created
D/CameraPreview(31322): resume()
D/CameraInstance(31322): Opening camera
D/CameraInstance(31322): Configuring camera
I/CameraManager(31322): Camera Display Orientation: 90
I/CameraManager(31322): Initial camera parameters: preview-size=1920x1080;video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;video-size-values=3840x2160,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(15000,30000),(30000,30000);preview-frame-rate-values=15,30;picture-size=4032x3024;picture-size-values=4032x3024,4032x2268,4000x3000,4000x2000,3840x2160,3264x2448,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,246x184,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,50hz,60hz,auto;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.38;horizontal-view-angle=65.5941;vertical-view-angle=51.5878;exposure-compensation=0;max-exposure-compensation=24;min-exposure-compensation=-24;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,106,112,118,124,130,136,142,148,154,160,166,172,178,184,190,196,203,209,215,221,227,233,239,245,251,257,263,269,275,281,287,293,299,306,312,318,324,330,336,342,348,354,360,366,372,378,384,390,396,403,409,415,421,427,433,439,445,451,457,463,469,475,481,487,493,499,506,512,518,524,530,536,542,548,554,560,566,572,578,584,590,596,603,609,615,621,627,633,639,645,651,657,663,669,675,681,687,693,699;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true
I/CameraConfiguration(31322): Requesting focus mode value from among: [auto]
I/CameraConfiguration(31322): Supported focus mode values: [infinity, auto, macro, continuous-video, continuous-picture]
I/CameraConfiguration(31322): Can set focus mode to: auto
I/CameraConfiguration(31322): Focus mode already set to auto
I/CameraConfiguration(31322): Requesting flash mode value from among: [off]
I/CameraConfiguration(31322): Supported flash mode values: [off, auto, on, torch, red-eye]
I/CameraConfiguration(31322): Can set flash mode to: off
I/CameraConfiguration(31322): Flash mode already set to off
I/PreviewScalingStrategy(31322): Viewfinder size: 825x825
I/PreviewScalingStrategy(31322): Preview in order of preference: [1024x768, 1280x960, 1440x1080, 800x600, 1600x1200, 1280x720, 1920x1440, 640x480, 1920x1080, 1920x960, 720x480, 352x288, 640x360, 320x240, 176x144]
I/CameraManager(31322): Final camera parameters: video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;video-size-values=3840x2160,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(15000,30000),(30000,30000);preview-frame-rate-values=15,30;picture-size=4032x3024;picture-size-values=4032x3024,4032x2268,4000x3000,4000x2000,3840x2160,3264x2448,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,246x184,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,50hz,60hz,auto;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.38;horizontal-view-angle=65.5941;vertical-view-angle=51.5878;exposure-compensation=0;max-exposure-compensation=24;min-exposure-compensation=-24;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,106,112,118,124,130,136,142,148,154,160,166,172,178,184,190,196,203,209,215,221,227,233,239,245,251,257,263,269,275,281,287,293,299,306,312,318,324,330,336,342,348,354,360,366,372,378,384,390,396,403,409,415,421,427,433,439,445,451,457,463,469,475,481,487,493,499,506,512,518,524,530,536,542,548,554,560,566,572,578,584,590,596,603,609,615,621,627,633,639,645,651,657,663,669,675,681,687,693,699;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;preview-size=1024x768
I/CenterCropStrategy(31322): Preview: 768x1024; Scaled: 825x1100; Want: 825x825
I/CameraPreview(31322): Starting preview
D/CameraInstance(31322): Starting preview
I/AutoFocusManager(31322): Current focus mode 'auto'; use auto focus? true
I/flutter (31322): navigating to next screen
I/flutter (31322): Build second screen
D/CameraPreview(31322): resume()
D/CameraInstance(31322): Opening camera
D/CameraPreview(31322): resume()
W/CameraPreview(31322): initCamera called twice
I/flutter (31322): created
E/Camera  (31322): Error 2
D/CameraInstance(31322): Configuring camera
I/CameraManager(31322): Camera Display Orientation: 90
I/CameraManager(31322): Initial camera parameters: preview-size=1920x1080;video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;video-size-values=3840x2160,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(15000,30000),(30000,30000);preview-frame-rate-values=15,30;picture-size=4032x3024;picture-size-values=4032x3024,4032x2268,4000x3000,4000x2000,3840x2160,3264x2448,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,246x184,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,50hz,60hz,auto;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.38;horizontal-view-angle=65.5941;vertical-view-angle=51.5878;exposure-compensation=0;max-exposure-compensation=24;min-exposure-compensation=-24;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,106,112,118,124,130,136,142,148,154,160,166,172,178,184,190,196,203,209,215,221,227,233,239,245,251,257,263,269,275,281,287,293,299,306,312,318,324,330,336,342,348,354,360,366,372,378,384,390,396,403,409,415,421,427,433,439,445,451,457,463,469,475,481,487,493,499,506,512,518,524,530,536,542,548,554,560,566,572,578,584,590,596,603,609,615,621,627,633,639,645,651,657,663,669,675,681,687,693,699;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true
I/CameraConfiguration(31322): Requesting focus mode value from among: [auto]
I/CameraConfiguration(31322): Supported focus mode values: [infinity, auto, macro, continuous-video, continuous-picture]
I/CameraConfiguration(31322): Can set focus mode to: auto
I/CameraConfiguration(31322): Focus mode already set to auto
I/CameraConfiguration(31322): Requesting flash mode value from among: [off]
I/CameraConfiguration(31322): Supported flash mode values: [off, auto, on, torch, red-eye]
I/CameraConfiguration(31322): Can set flash mode to: off
I/CameraConfiguration(31322): Flash mode already set to off
I/PreviewScalingStrategy(31322): Viewfinder size: 825x825
I/PreviewScalingStrategy(31322): Preview in order of preference: [1024x768, 1280x960, 1440x1080, 800x600, 1600x1200, 1280x720, 1920x1440, 640x480, 1920x1080, 1920x960, 720x480, 352x288, 640x360, 320x240, 176x144]
I/CameraManager(31322): Final camera parameters: video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;video-size-values=3840x2160,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240,176x144;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=15000,30000;preview-fps-range-values=(15000,15000),(15000,30000),(30000,30000);preview-frame-rate-values=15,30;picture-size=4032x3024;picture-size-values=4032x3024,4032x2268,4000x3000,4000x2000,3840x2160,3264x2448,3264x1836,2688x1512,2592x1944,2560x1280,2048x1536,1920x1440,1920x1080,1920x960,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,352x288,320x240;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,246x184,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none;antibanding=auto;antibanding-values=off,50hz,60hz,auto;flash-mode=off;flash-mode-values=off,auto,on,torch,red-eye;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.38;horizontal-view-angle=65.5941;vertical-view-angle=51.5878;exposure-compensation=0;max-exposure-compensation=24;min-exposure-compensation=-24;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,106,112,118,124,130,136,142,148,154,160,166,172,178,184,190,196,203,209,215,221,227,233,239,245,251,257,263,269,275,281,287,293,299,306,312,318,324,330,336,342,348,354,360,366,372,378,384,390,396,403,409,415,421,427,433,439,445,451,457,463,469,475,481,487,493,499,506,512,518,524,530,536,542,548,554,560,566,572,578,584,590,596,603,609,615,621,627,633,639,645,651,657,663,669,675,681,687,693,699;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;preview-size=1024x768
I/CenterCropStrategy(31322): Preview: 768x1024; Scaled: 825x1100; Want: 825x825
I/CameraPreview(31322): Starting preview
D/CameraInstance(31322): Starting preview
I/AutoFocusManager(31322): Current focus mode 'auto'; use auto focus? true
W/AutoFocusManager(31322): Unexpected exception while focusing
W/AutoFocusManager(31322): java.lang.RuntimeException: autoFocus failed
W/AutoFocusManager(31322): 	at android.hardware.Camera.native_autoFocus(Native Method)
W/AutoFocusManager(31322): 	at android.hardware.Camera.autoFocus(Camera.java:1385)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.focus(AutoFocusManager.java:101)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.access$100(AutoFocusManager.java:31)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager$1.handleMessage(AutoFocusManager.java:57)
W/AutoFocusManager(31322): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/AutoFocusManager(31322): 	at android.os.Looper.loop(Looper.java:223)
W/AutoFocusManager(31322): 	at android.os.HandlerThread.run(HandlerThread.java:67)
W/AutoFocusManager(31322): Unexpected exception while focusing
W/AutoFocusManager(31322): java.lang.RuntimeException: autoFocus failed
W/AutoFocusManager(31322): 	at android.hardware.Camera.native_autoFocus(Native Method)
W/AutoFocusManager(31322): 	at android.hardware.Camera.autoFocus(Camera.java:1385)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.focus(AutoFocusManager.java:101)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager.access$100(AutoFocusManager.java:31)
W/AutoFocusManager(31322): 	at com.journeyapps.barcodescanner.camera.AutoFocusManager$1.handleMessage(AutoFocusManager.java:57)
W/AutoFocusManager(31322): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/AutoFocusManager(31322): 	at android.os.Looper.loop(Looper.java:223)
W/AutoFocusManager(31322): 	at android.os.HandlerThread.run(HandlerThread.java:67)
D/CameraPreview(31322): resume()
W/CameraPreview(31322): initCamera called twice
D/CameraPreview(31322): pause()
D/CameraInstance(31322): Closing camera
D/CameraInstance(31322): Camera is closed, not requesting preview   <--- Here I would like to have the preview again.
```

**Comment by enricobenedos** [comment]
Hey @ChristianNavolskyi,

I understood your explanation. Can you please provide a sample code/project in order to debug this problem? This can help us to reduce dead times.

Thank you

**Comment by ChristianNavolskyi** [comment]
Hey @enricobenedos,

that was a quick reply. The sample project is linked under **Additional context**.
But here it is again: https://github.com/ChristianNavolskyi/qr_code_issue

Thanks 🙂

**Comment by enricobenedos** [comment]
Sorry @ChristianNavolskyi,

I'm so used to ask for a sample project that I don't see the attached one😅

I will check your project to help you find a solution.

**Comment by ChristianNavolskyi** [comment]
No problem 😄 and thank you very much!

**Comment by enricobenedos** [comment]
On my iPhone XS with iOS 14 it works perfectly. 

But I advice you to convert your `Stateless` widgets to `Statefull` in order to assign a controller to `QRView` widget as in the package sample. Then you also need to override `dispose()` method and call `QRView` controller dispose (as in the sample).  I'm not sure but it can be an idea due to the fact that your error can be caused to a not disposed `QRView` widget. Unfortunately I have not a Android 11 device, but try with my advices and then tell me if it works.

_Your project does not have the iOS configuration and crash at startup_
```xml
<key>io.flutter.embedded_views_preview</key>
<true/>
<key>NSCameraUsageDescription</key>
<string>This app needs camera access to scan QR codes</string>
```

**Comment by juliansteenbakker** [comment]
Version 0.3.0 had some issues with the camera activity which has been solved with v0.3.1. Please check if the issue still persists on version 0.3.1.

**Comment by ChristianNavolskyi** [comment]
I just updated the code to use `StatefulWidget` and the `dispose()` method to dispose the `QRViewController`s. Also bumped the version to 0.3.1 but sadly the same issue persists.

The problem also occurs in the Android emulator, in case you want to try to reproduce it with an Android "device".

**Comment by juliansteenbakker** [comment]
After some testing i've discovered that this only happens on Android and is caused by the underlaying ZXING framework. 

So there are 2 issues here. The first one is the autofocus error thats continuesly being logged. This can be solved by pausing the QRView before navigation to the second page:
```
             MaterialButton(
              onPressed: () {
                _qrController.pauseCamera();
                print("navigating to next screen");
                Navigator.of(context).pushNamed("/other");
                // Future.delayed(Duration(seconds: 5), () => Navigator.of(context).pushNamed("/other"));
              },
```

The second issue is the freezing when navigating back. This is caused by the framework pausing the QRView on the first page. I don't really know why it's happening, and i also don't know how to trigger a piece of code when navigating back with the appbar back button but if you execute  `_qrController?.resumeCamera();` the QRView continues to work. I have tested with the following code snippet from your example:
```
            SizedBox(
              width: 300,
              height: 300,
              child: QRView(key: _qrKey, onQRViewCreated: (controller) => _qrController = controller),
            ),
            MaterialButton(
              onPressed: () {
                _qrController.pauseCamera();
                print("navigating to next screen");
                Navigator.of(context).pushNamed("/other");
              },
              child: Text("Go to other"),
            ),
            MaterialButton(
              onPressed: () {
                _qrController.resumeCamera();
              },
              child: Text("Resume"),
            ),
```

**Comment by ChristianNavolskyi** [comment]
It works 🤩 
Those two calls fixed the problems.

Thank you very much. 🙂 

PS: To call code when coming back to the first screen I used [focus_detector](https://github.com/EdsonBueno/focus_detector) (hope it's not a problem to mention it here).

**Comment by juliansteenbakker** [comment]
You can get it working without an external library. I was working on another bug while i encountered this issue and i found a solution to it. (#250)

> The last issue is that when you pause the camera before opening the second screen and you call navigator.pop, it returns to the first qrview however it's paused. This can be solved by adding a return value to the navigator.pop(), so that we can check when that value is returned and resume the camera. I made an example using @luanssd example code.

**main.dart**

```dart
  Future<void> _onQRViewCreated(QRViewController controller) async {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) async {
      await controller.pauseCamera();
      if (!qrViewOpened) {
        qrViewOpened = true;
        var secondScreen = await Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => DetailTest(result: scanData.code)));
        if (secondScreen) {
          qrViewOpened = false;
          await controller.resumeCamera();
        }
      }
    });
  }
```
**detail_test.dart**
Note: onTap: () => Navigator.of(context).pop(true),
```dart
import 'package:flutter/material.dart';

class DetailTest extends StatefulWidget {
  const DetailTest({
    Key key,
    this.result,
  }) : super(key: key);
  final result;

  @override
  State<StatefulWidget> createState() => DetailTestPage();
}

class DetailTestPage extends State<DetailTest> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          elevation: 0.3,
          centerTitle: true,
          leading: GestureDetector(
            onTap: () => Navigator.of(context).pop(true),
            child: Padding(
              padding: EdgeInsets.symmetric(
                horizontal: 20,
              ),
              child: CircleAvatar(
                backgroundColor: Colors.transparent,
                radius: 14,
                child: Icon(
                  Icons.arrow_back_ios,
                  color: Colors.white,
                  size: 28,
                ),
              ),
            ),
          ),
          title: Text("DetailTestPage"),
          actions: <Widget>[],
        ),
        body: Container(
            alignment: Alignment.center,
            margin: EdgeInsets.only(top: 20, left: 0, right: 0),
            child: Column(children: <Widget>[
              Center(
                child: Text('Detail result'),
              ),
              Container(
                child: Text('${widget.result}'),
              ),
            ])));
  }
}
```
