### ISSUE TITLE
[BUG] Android App crash while opening QR View.

### ISSUE THREAD

**Issue by DhavalRKansara** [juliuscanute/qr_code_scanner#268]
**Describe the bug**
I have used this plugin in my app and Android app get crashed when I tried to open QRView.

**Flutter information**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.2.1 20D74 darwin-x64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (2 available)

• No issues found!
```

**Device (please complete the following information):**
 - Device: Pixel
 - OS: Android Version: 10

**Code**
```
class ScanQrScreen extends StatefulWidget {
  @override
  _ScanQrScreenState createState() => _ScanQrScreenState();
}

class _ScanQrScreenState extends State<ScanQrScreen> {

  QRViewController controller;
  final GlobalKey qrKey = GlobalKey(debugLabel: 'QR');

  // In order to get hot reload to work we need to pause the camera if the platform
  // is android, or resume the camera if the platform is iOS.
  @override
  void reassemble() {
    super.reassemble();
    if (Platform.isAndroid) {
      controller.pauseCamera();
    }
    controller.resumeCamera();
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return _buildQrView(context);
  }


  Widget _buildQrView(BuildContext context) {

    var scanArea =  300.0;

    // To ensure the Scanner view is properly sizes after rotation
    // we need to listen for Flutter SizeChanged notification and update controller
    return QRView(
      key: qrKey,
      onQRViewCreated: _onQRViewCreated,
      overlay: QrScannerOverlayShape(
          borderColor: Colors.red,
          borderRadius: 10,
          borderLength: 30,
          borderWidth: 10,
          cutOutSize: scanArea),
    );
  }


  void _onQRViewCreated(QRViewController controller) {
    setState(() {
      this.controller = controller;
    });
    controller.scannedDataStream.listen((scanData) {
      Navigator.of(context).pop(scanData.code);
    });
  }
}
```
**Error:**
```
W/Gralloc3(15686): allocator 3.x is not supported
D/CameraPreview(15686): resume()
D/CameraInstance(15686): Opening camera
D/CameraInstance(15686): Configuring camera
I/CameraManager(15686): Camera Display Orientation: 90
I/CameraManager(15686): Initial camera parameters: preview-size=1920x1080;video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;video-size-values=3840x2160,2592x1944,2688x1512,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate-values=15,24,30;picture-size=4048x3036;picture-size-values=4048x3036,4000x3000,3840x2160,3264x2448,3200x2400,2976x2976,2592x1944,2688x1512,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua;antibanding=auto;antibanding-values=off,60hz,50hz,auto;scene-mode=auto;scene-mode-values=auto,landscape,snow,beach,sunset,night,portrait,sports,steadyphoto,candlelight,fireworks,party,night-portrait,theatre,action,;flash-mode=off;flash-mode-values=off,auto,on,torch;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.67;horizontal-view-angle=67.7846;vertical-view-angle=53.4809;exposure-compensation=0;max-exposure-compensation=12;min-exposure-compensation=-12;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,148,151,154,157,160,163,166,169,172,175,178,181,184,187,190,193,196,199,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,303,306,309,312,315,318,321,324,327,330,333,336,339,342,345,348,351,354,357,360,363,366,369,372,375,378,381,384,387,390,393,396,399;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true
I/CameraConfiguration(15686): Requesting focus mode value from among: [auto]
I/CameraConfiguration(15686): Supported focus mode values: [infinity, auto, macro, continuous-video, continuous-picture]
I/CameraConfiguration(15686): Can set focus mode to: auto
I/CameraConfiguration(15686): Focus mode already set to auto
I/CameraConfiguration(15686): Requesting flash mode value from among: [off]
I/CameraConfiguration(15686): Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration(15686): Can set flash mode to: off
I/CameraConfiguration(15686): Flash mode already set to off
I/PreviewScalingStrategy(15686): Viewfinder size: 1647x1080
I/PreviewScalingStrategy(15686): Preview in order of preference: [1920x1080, 1600x1200, 1440x1080, 2048x1536, 1280x960, 1280x720, 1024x768, 720x480, 800x600, 640x480, 640x360, 480x320, 480x360, 352x288, 320x240, 176x144, 160x120]
I/CameraManager(15686): Final camera parameters: video-size=1920x1080;preferred-preview-size-for-video=1920x1080;preview-size-values=2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;video-size-values=3840x2160,2592x1944,2688x1512,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;preview-format=yuv420sp;preview-format-values=yuv420p,yuv420sp,;preview-frame-rate=30;preview-fps-range=7000,30000;preview-fps-range-values=(15000,15000),(24000,24000),(7000,30000),(30000,30000);preview-frame-rate-values=15,24,30;picture-size=4048x3036;picture-size-values=4048x3036,4000x3000,3840x2160,3264x2448,3200x2400,2976x2976,2592x1944,2688x1512,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x720,1024x768,800x600,720x480,640x480,640x360,480x360,480x320,352x288,320x240,176x144,160x120;picture-format=jpeg;picture-format-values=jpeg;jpeg-thumbnail-width=320;jpeg-thumbnail-height=240;jpeg-thumbnail-size-values=0x0,176x144,240x144,256x144,240x160,256x154,240x240,320x240;jpeg-thumbnail-quality=90;jpeg-quality=90;rotation=0;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua;antibanding=auto;antibanding-values=off,60hz,50hz,auto;scene-mode=auto;scene-mode-values=auto,landscape,snow,beach,sunset,night,portrait,sports,steadyphoto,candlelight,fireworks,party,night-portrait,theatre,action,;flash-mode=off;flash-mode-values=off,auto,on,torch;focus-mode=auto;focus-mode-values=infinity,auto,macro,continuous-video,continuous-picture;max-num-focus-areas=1;focus-areas=(0,0,0,0,0);focal-length=4.67;horizontal-view-angle=67.7846;vertical-view-angle=53.4809;exposure-compensation=0;max-exposure-compensation=12;min-exposure-compensation=-12;exposure-compensation-step=0.166667;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;max-num-metering-areas=1;metering-areas=(0,0,0,0,0);zoom=0;max-zoom=99;zoom-ratios=100,103,106,109,112,115,118,121,124,127,130,133,136,139,142,145,148,151,154,157,160,163,166,169,172,175,178,181,184,187,190,193,196,199,203,206,209,212,215,218,221,224,227,230,233,236,239,242,245,248,251,254,257,260,263,266,269,272,275,278,281,284,287,290,293,296,299,303,306,309,312,315,318,321,324,327,330,333,336,339,342,345,348,351,354,357,360,363,366,369,372,375,378,381,384,387,390,393,396,399;zoom-supported=true;smooth-zoom-supported=false;focus-distances=Infinity,Infinity,Infinity;max-num-detected-faces-hw=10;max-num-detected-faces-sw=0;video-frame-format=android-opaque;recording-hint=false;video-snapshot-supported=true;video-stabilization=false;video-stabilization-supported=true;preview-size=1920x1080
I/CenterCropStrategy(15686): Preview: 1080x1920; Scaled: 1080x1920; Want: 1080x1647
I/CameraPreview(15686): Starting preview
D/CameraInstance(15686): Starting preview
D/AndroidRuntime(15686): Shutting down VM
E/AndroidRuntime(15686): FATAL EXCEPTION: main
E/AndroidRuntime(15686): Process: com.medpharm.ipsgo, PID: 15686
E/AndroidRuntime(15686): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/zxing/ResultPointCallback;
E/AndroidRuntime(15686): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView.kt:201)
E/AndroidRuntime(15686): 	at net.touchcapture.qr.flutterqr.QRView.getView(QRView.kt:196)
E/AndroidRuntime(15686): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:189)
E/AndroidRuntime(15686): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:421)
E/AndroidRuntime(15686): 	at android.app.Dialog.show(Dialog.java:315)
E/AndroidRuntime(15686): 	at android.app.Presentation.show(Presentation.java:250)
E/AndroidRuntime(15686): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime(15686): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime(15686): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/AndroidRuntime(15686): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/AndroidRuntime(15686): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(15686): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(15686): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime(15686): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/AndroidRuntime(15686): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(15686): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(15686): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(15686): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(15686): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15686): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(15686): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(15686): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.zxing.ResultPointCallback" on path: DexPathList[[zip file "/data/app/com.medpharm.ipsgo-37FfnzMBsm30-I1lee1OsQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.medpharm.ipsgo-37FfnzMBsm30-I1lee1OsQ==/lib/arm64, /data/app/com.medpharm.ipsgo-37FfnzMBsm30-I1lee1OsQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
E/AndroidRuntime(15686): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(15686): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15686): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15686): 	... 21 more
I/Process (15686): Sending signal. PID: 15686 SIG: 9
Lost connection to device.
```

**Comment by jnickzlim** [comment]
I am having similar issue, how do you resolve it?

**Comment by DhavalRKansara** [comment]
@jnickzlim Actually earlier I have added the below lines in my `app/build.gradle`. I tried multiple QR code libraries so maybe I added these lines to use those packages... But after removing it issue was fixed.

```
    configurations {
        all*.exclude group: 'com.google.zxing'
    }
```
