### ISSUE TITLE
Crash after permission of camera 

### ISSUE THREAD

**Issue by nitneuq33** [juliuscanute/qr_code_scanner#29]
Hello I have a crash after accept permissin of the camera. 

here is the repport :

```
D/CameraPreview( 6772): resume()
W/CameraPreview( 6772): initCamera called twice
D/SensorManager( 6772): unregisterListener ::   
D/SensorManager( 6772): registerListener :: 1, K6DS3TR Acceleration Sensor, 200000, 0,  
D/CameraPreview( 6772): pause()
D/CameraInstance( 6772): Closing camera
D/SensorManager( 6772): unregisterListener ::   
V/InputMethodManager( 6772): Not IME target window, ignoring
D/ViewRootImpl@2e52b00[MainActivity]( 6772): dispatchAttachedToWindow
V/Surface ( 6772): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@2e52b00[MainActivity]( 6772): Relayout returned: old=[0,0][0,0] new=[0,0][696,996] result=0x7 surface={valid=true 504886788096} changed=true
D/mali_winsys( 6772): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [696x996]-format:1
D/OpenGLRenderer( 6772): eglCreateWindowSurface = 0x75b8428a50
D/ViewRootImpl@2e52b00[MainActivity]( 6772): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 696, 996) ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl@32cd41e[MainActivity]( 6772): MSG_WINDOW_FOCUS_CHANGED 0
V/Surface ( 6772): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@32cd41e[MainActivity]( 6772): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager( 6772): Starting input: tba=android.view.inputmethod.EditorInfo@d9f8edf nm : fr.test.testmaj ic=null
I/InputMethodManager( 6772): startInputInner - mService.startInputOrWindowGainedFocus
D/AndroidRuntime( 6772): Shutting down VM
E/AndroidRuntime( 6772): FATAL EXCEPTION: main
E/AndroidRuntime( 6772): Process: fr.test.testmaj, PID: 6772
E/AndroidRuntime( 6772): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=513469796, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {fr.test.testmaj/fr.test.testmaj.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime( 6772): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
E/AndroidRuntime( 6772): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
E/AndroidRuntime( 6772): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime( 6772): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime( 6772): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 6772): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 6772): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime( 6772): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6772): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 6772): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 6772): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void java.lang.Runnable.run()' on a null object reference
E/AndroidRuntime( 6772): 	at io.flutter.plugins.camera.CameraPlugin$CameraRequestPermissionsListener.onRequestPermissionsResult(CameraPlugin.java:230)
E/AndroidRuntime( 6772): 	at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime( 6772): 	at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:127)
E/AndroidRuntime( 6772): 	at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
E/AndroidRuntime( 6772): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7737)
E/AndroidRuntime( 6772): 	at android.app.Activity.dispatchActivityResult(Activity.java:7560)
E/AndroidRuntime( 6772): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
E/AndroidRuntime( 6772): 	... 9 more
```

After crash I can launch Qrview normaly but, just crash one time at the permission choice.

More info : I use the plugin in an alertedialog
Thank you

**Comment by juliansteenbakker** [comment]
Please comment if this issue still persists on 0.1.0.

**Comment by hediehrouhi** [comment]
Hello  I have this problem as well right now. How can I fix it?

**Comment by bhanuka96** [comment]
same issue.

You can reproduce this issue this way.

1. display QR Scanner, after finding the `result` navigate to the next page. And load `CameraPreview` using `camera plugin` on current page
