### ISSUE TITLE
[BUG]  Multiple starts

### ISSUE THREAD

**Issue by LiJian0129** [juliuscanute/qr_code_scanner#294]
White screen appears after multiple starts

C:\Users\Prent>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale zh-CN)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Prent\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Prent\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • SM G9700 (mobile) • R28M710LYVM • android-arm64  • Android 10 (API 29)

https://user-images.githubusercontent.com/13675229/112439222-d218b980-8d83-11eb-80ff-134cbaf1cafb.mp4

Failed to handle method call
    java.lang.SecurityException: Neither user 10412 nor current process has android.permission.WAKE_LOCK.
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1299)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1079)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:450)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:473)
        at android.app.Presentation.show(Presentation.java:283)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:2002)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:7759)
        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3255)
        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3221)
2021-03-25 16:06:15.922 4153-4153/com.simon.simon_installer V/InputMethodManager: Not IME target window, ignoring
2021-03-25 16:06:15.923 4153-4201/com.simon.simon_installer E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Neither user 10412 nor current process has android.permission.WAKE_LOCK., null, java.lang.SecurityException: Neither user 10412 nor current process has android.permission.WAKE_LOCK.
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1299)
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1079)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:450)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
        at android.app.Dialog.show(Dialog.java:473)
        at android.app.Presentation.show(Presentation.java:283)
        at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
        at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
        at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
        at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:8016)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:2002)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2030)
        at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:7759)
        at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3255)
        at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3221)
    
    )
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1036:18)
    <asynchronous suspension>
    #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:742:5)
    <asynchronous suspension>
    #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:195:7)

**Comment by lazarohcm** [comment]
I'm facing the exact same problem

**Comment by juliansteenbakker** [comment]
I think the problem is the view is not disposing correctly. Can you try again with the new MLKit scanner?

**Comment by cmsong-shina** [comment]
Similar here when I touch `QRView` quickly several times, view turned to black.

And exception claim `android.permission.WAKE_LOCK`



*debug console*

```debug console
D/CameraPreview(30170): resume()
W/CameraPreview(30170): initCamera called twice
D/SensorManager(30170): unregisterListener ::
D/SensorManager(30170): registerListener :: 1, LSM6DSL Acceleration Sensor, 200000, 0,
D/CameraPreview(30170): resume()
W/CameraPreview(30170): initCamera called twice
D/SensorManager(30170): unregisterListener ::
D/SensorManager(30170): registerListener :: 1, LSM6DSL Acceleration Sensor, 200000, 0,
D/Dialog  (30170): mIsSamsungBasicInteraction = false
D/Dialog  (30170): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
D/CameraPreview(30170): resume()
W/CameraPreview(30170): initCamera called twice
D/SensorManager(30170): unregisterListener ::
D/SensorManager(30170): registerListener :: 1, LSM6DSL Acceleration Sensor, 200000, 0,
D/PhoneWindow(30170): forceLight changed to true [] from com.android.internal.policy.PhoneWindow.updateForceLightNavigationBar:4274 com.android.internal.policy.DecorView.updateColorViews:1547 com.android.internal.policy.PhoneWindow.dispatchWindowAttributesChanged:3252 android.view.Window.setFlags:1153 com.android.internal.policy.PhoneWindow.generateLayout:2474
I/MultiWindowDecorSupport(30170): [INFO] isPopOver = false
I/MultiWindowDecorSupport(30170): updateCaptionType >> DecorView@2e3b0b1[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(30170): setCaptionType = 0, DecorView = DecorView@2e3b0b1[]
I/ViewRootImpl@dbe1fb3[MainActivity](30170): setView = com.android.internal.policy.DecorView@2e3b0b1 TM=true MM=false
I/mali_egl(30170): eglDestroySurface() in
```

**Comment by C-8** [comment]
@juliansteenbakker 
I am still facing the problem described with the newest version ( 0.5.1 ).

Stacktrace: 
```

E/flutter (20310): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(error, Neither user 10284 nor current process has android.permission.WAKE_LOCK., null, java.lang.SecurityException: Neither user 10284 nor current process has android.permission.WAKE_LOCK.
E/flutter (20310): 	at android.os.Parcel.createException(Parcel.java:2071)
E/flutter (20310): 	at android.os.Parcel.readException(Parcel.java:2039)
E/flutter (20310): 	at android.os.Parcel.readException(Parcel.java:1987)
E/flutter (20310): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
E/flutter (20310): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:889)
E/flutter (20310): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
E/flutter (20310): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
E/flutter (20310): 	at android.app.Dialog.show(Dialog.java:342)
E/flutter (20310): 	at android.app.Presentation.show(Presentation.java:257)
E/flutter (20310): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/flutter (20310): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/flutter (20310): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/flutter (20310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (20310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (20310): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (20310): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (20310): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (20310): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (20310): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (20310): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (20310): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/flutter (20310): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (20310): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (20310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/flutter (20310): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (20310): 	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
E/flutter (20310): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
E/flutter (20310): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4304)
E/flutter (20310): 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2127)
E/flutter (20310): 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2093)
E/flutter (20310): 
E/flutter (20310): )
E/flutter (20310): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (20310): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (20310): <asynchronous suspension>
E/flutter (20310): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1043:18)
E/flutter (20310): <asynchronous suspension>
E/flutter (20310): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:748:5)
E/flutter (20310): <asynchronous suspension>
E/flutter (20310): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:193:7)
E/flutter (20310): <asynchronous suspension>
```

This happens when the application is awake and not when the AppLifecycleState changes from paused to resume.

**Comment by loreberti89** [comment]
I have same problem, and for me, is when I "rebuild" father of My Camera Widget.
have you found a solution?

**Comment by nicolaspernoud** [comment]
I have the same problem as well... It seems that pausing the camera before popping off the camera widget mitigate the problem...

**Comment by cs-nuuk** [comment]
This is still broken in v0.6.1.

The only solution that worked for me was to disable orientation change and wait 100ms before I open the barcode scanner screen.
