### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yoyo89757001** [juliuscanute/qr_code_scanner#330]
**Describe the bug**

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

**Device (please complete the following information):**

**Screenshots**

**Additional context**

 --------- beginning of crash
2021-06-04 08:09:20.836 14553-14553/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhiyijian.zhiyijian_iot, PID: 14553
    java.lang.RuntimeException: java.lang.NoSuchMethodException: b.e.b.e.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at com.journeyapps.barcodescanner.A.a(Unknown Source:4)
        at com.journeyapps.barcodescanner.BarcodeView.E(:2)
        at com.journeyapps.barcodescanner.BarcodeView.I(Unknown Source:21)
        at com.journeyapps.barcodescanner.BarcodeView.w(Unknown Source:0)
        at com.journeyapps.barcodescanner.q.A(Unknown Source:28)
        at com.journeyapps.barcodescanner.q.B(Unknown Source:48)
        at com.journeyapps.barcodescanner.q.d(:5)
        at com.journeyapps.barcodescanner.m.handleMessage(Unknown Source:13)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7563)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
     Caused by: java.lang.NoSuchMethodException: b.e.b.e.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at com.journeyapps.barcodescanner.A.a(Unknown Source:4) 
        at com.journeyapps.barcodescanner.BarcodeView.E(:2) 
        at com.journeyapps.barcodescanner.BarcodeView.I(Unknown Source:21) 
        at com.journeyapps.barcodescanner.BarcodeView.w(Unknown Source:0) 
        at com.journeyapps.barcodescanner.q.A(Unknown Source:28) 
        at com.journeyapps.barcodescanner.q.B(Unknown Source:48) 
        at com.journeyapps.barcodescanner.q.d(:5) 
        at com.journeyapps.barcodescanner.m.handleMessage(Unknown Source:13) 
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.app.ActivityThread.main(ActivityThread.java:7563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)

**Comment by yoyo89757001** [comment]
debug 直装不会报错。 打包后报错闪退

**Comment by yoyo89757001** [comment]
安卓，10  小米9A

**Comment by yoyo89757001** [comment]
An error occurred after packaging

**Comment by yoyo89757001** [comment]
Debug runs fine

**Comment by juliansteenbakker** [comment]
https://github.com/juliuscanute/qr_code_scanner/issues/282#issuecomment-811783947
> if anyone facing the same problem you can find the solution here :
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception
