### ISSUE TITLE
[BUG] Crash on device android

### ISSUE THREAD

**Issue by hphuc613** [juliuscanute/qr_code_scanner#420]
My app working fine on emulator, but I build apk release and install in any physical device is crash and out the app when open camera. Please help me.

**Comment by MTM-A** [comment]
I have the same problem too.
is a solution foreseen in a short time?

**Comment by hphuc613** [comment]
> I have the same problem too.
> is a solution foreseen in a short time?



> I have the same problem too.
> is a solution foreseen in a short time?

https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception
I see solution in case it relate to proguard

**Comment by tehsunnliu** [comment]
Hi, I just discovered this bug, and it crashes the whole app. Even while running on a real device while debugging.

```
E/AndroidRuntime(  891): FATAL EXCEPTION: DecoderThread
E/AndroidRuntime(  891): Process: com.sunnstech.raph.client, PID: 891
E/AndroidRuntime(  891): java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(  891): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
E/AndroidRuntime(  891): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
E/AndroidRuntime(  891): 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
E/AndroidRuntime(  891): 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
E/AndroidRuntime(  891): 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
E/AndroidRuntime(  891): 	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
E/AndroidRuntime(  891): 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
E/AndroidRuntime(  891): 	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
E/AndroidRuntime(  891): 	at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
E/AndroidRuntime(  891): 	at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
E/AndroidRuntime(  891): 	at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
E/AndroidRuntime(  891): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime(  891): 	at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime(  891): 	at android.os.HandlerThread.run(HandlerThread.java:61)
D/CameraPreview(  891): pause()

``` 
This happens only in my older device running Android 29 (6.0.1 MMB29M)
However, it works perfectly fine on my new device.

**Comment by greenking19** [comment]
> > I have the same problem too.
> > is a solution foreseen in a short time?
> 
> https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception I see solution in case it relate to proguard

🤔 Hello, I don't understand this solution a bit, where is the proguard in the flutter project. I am not very familiar with andorid

**Comment by hphuc613** [comment]
> > > I have the same problem too.
> > > is a solution foreseen in a short time?
> > 
> > 
> > https://stackoverflow.com/questions/54847976/java-lang-assertionerror-impossible-caused-by-java-lang-nosuchmethodexception I see solution in case it relate to proguard
> 
> 🤔 Hello, I don't understand this solution a bit, where is the proguard in the flutter project. I am not very familiar with andorid

https://stackoverflow.com/questions/52428973/how-to-minify-a-flutter-app-with-proguard
Please, add file proguard like solution.

**Comment by xncz8h** [comment]
> For those still experiencing the crash in release but debug is okay, the issue is been caused by when building a release process in gradle. The way i was able to fix is is by
> 
> 1. add the following to the android/app/build.gradle
>    ```
>    buildTypes {
>     release {
>         signingConfig signingConfigs.release
>    
>         minifyEnabled true
>         useProguard true
>    
>         proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>    
>     }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    }
> 
> The on the same path create a file proguard-rules.pro and add the following in it
> 
> ```
>     #Flutter Wrapper
>     -keep class io.flutter.app.** { *; }
>     -keep class io.flutter.plugin.**  { *; }
>     -keep class io.flutter.util.**  { *; }
>     -keep class io.flutter.view.**  { *; }
>     -keep class io.flutter.**  { *; }
>     -keep class io.flutter.plugins.**  { *; }
>     -keepclassmembers enum * {
>        public static **[] values();
>        public static ** valueOf(java.lang.String); 
>     }
> ```
> 
> This was able to fix my issue

This worked for us. However, we had to remove the line "useProguard true". This caused build errors
