### ISSUE TITLE
CRASH -> Fatal Exception: java.lang.ArithmeticException divide by zero

### ISSUE THREAD

**Issue by Cayke** [juliuscanute/qr_code_scanner#43]
Getting many crashes with this error. Think it is caused by ZXing package. Check https://github.com/journeyapps/zxing-android-embedded/issues/334

Error:

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.j + 71(CameraPreview.java:71)
       at com.journeyapps.barcodescanner.CameraPreview.b + 6(CameraPreview.java:6)
       at com.journeyapps.barcodescanner.CameraPreview.access$300(CameraPreview.java)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage + 12(CameraPreview.java:12)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at android.os.Looper.loop + 214(Looper.java:214)
       at android.app.ActivityThread.main + 7078(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 964(ZygoteInit.java:964)
```

**Comment by GuruJohn** [comment]
I'm also starting to see this crash on quite a few device.

Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:71)
       at com.journeyapps.barcodescanner.CameraPreview.b(CameraPreview.java:6)
       at com.journeyapps.barcodescanner.CameraPreview.access$300(CameraPreview.java)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:12)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7037)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by apastuhov** [comment]
Got same crash on next devices:

Android v9:
 - HUAWEI Y5 2019
 - moto g(6)
 - Mate 20 Pro
 - Galaxy A20e
 - P20 lite

Android v8:
 - v8.1.0 - Redmi S2
 - v8 - Mate 9

**qr_code_scanner: 0.0.12**
**camera: 0.5.7**
**Chance of occurrence is around 7% per 1000 sessions**

```
Fatal Exception: java.lang.ArithmeticException: divide by zero
       at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:85)
       at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:6)
       at com.journeyapps.barcodescanner.CameraPreview.previewStarted(CameraPreview.java)
       at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:12)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by FantaMagier** [comment]
> Got same crash on next devices:
> 
> Android v9:
> 
> * HUAWEI Y5 2019
> * moto g(6)
> * Mate 20 Pro
> * Galaxy A20e
> * P20 lite
> 
> Android v8:
> 
> * v8.1.0 - Redmi S2
> * v8 - Mate 9
> 
> **qr_code_scanner: 0.0.12**
> **camera: 0.5.7**
> 
> Chance of occurrence is around 7% per 1000 sessions in my use-case
> 
> ```
> Fatal Exception: java.lang.ArithmeticException: divide by zero
>        at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:85)
>        at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:6)
>        at com.journeyapps.barcodescanner.CameraPreview.previewStarted(CameraPreview.java)
>        at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:12)
>        at android.os.Handler.dispatchMessage(Handler.java:108)
>        at android.os.Looper.loop(Looper.java:216)
>        at android.app.ActivityThread.main(ActivityThread.java:7625)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
> ```

I have 100% the same problem.

**Comment by dspicher** [comment]
Hi.
I bumped zxing to 4.0.2 where the issue should be fixed. Can you test on top of current master?
