### ISSUE TITLE
[BUG] qr_code_scanner throws exception on Flutter web

### ISSUE THREAD

**Issue by i3games** [juliuscanute/qr_code_scanner#441]
**Describe the bug**
After granting permission to the camera, the following exception is thrown (qr_code_scanner 0.5.2 and 0.6.1). 

Code is the example code from: [https://pub.dev/packages/qr_code_scanner/example](https://pub.dev/packages/qr_code_scanner/example).

```
Performing hot restart...
Waiting for connection from debug service on Chrome...
Restarted application in 6,144ms.
Height of Platform View type: [QRVIEW-1634575378408] may not be set. Defaulting to `height: 100%`.
Set `style.height` to any appropriate value to stop this message.
Width of Platform View type: [QRVIEW-1634575378408] may not be set. Defaulting to `width: 100%`.
Set `style.width` to any appropriate value to stop this message.

======== Exception caught by scheduler library =====================================================
The following TypeErrorImpl was thrown during a scheduler callback:
Unexpected null value.

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
lib/_engine/engine/canvaskit/embedded_views.dart 385:70                           submitFrame
lib/_engine/engine/canvaskit/rasterizer.dart 36:33                                draw
lib/_engine/engine/platform_dispatcher.dart 577:7                                 render
lib/ui/src/ui/window.dart 93:50                                                   render
packages/flutter/src/rendering/view.dart 229:15                                   compositeFrame
packages/flutter/src/rendering/binding.dart 457:18                                drawFrame
packages/flutter/src/widgets/binding.dart 883:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 319:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1143:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1080:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                                 [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1003:13                               invoke
lib/_engine/engine/platform_dispatcher.dart 157:5                                 invokeOnDrawFrame
lib/_engine/engine.dart 440:45                                                    <fn>
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following StateError was thrown during a scheduler callback:
Bad state: PictureRecorder is not recording

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
lib/_engine/engine/canvaskit/picture_recorder.dart 31:7                       endRecording
lib/_engine/engine/canvaskit/embedded_views.dart 358:35                       submitFrame
lib/_engine/engine/canvaskit/rasterizer.dart 36:33                            draw
lib/_engine/engine/platform_dispatcher.dart 577:7                             render
lib/ui/src/ui/window.dart 93:50                                               render
packages/flutter/src/rendering/view.dart 229:15                               compositeFrame
packages/flutter/src/rendering/binding.dart 457:18                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 319:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1143:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1080:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1003:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 157:5                             invokeOnDrawFrame
lib/_engine/engine.dart 440:45                                                <fn>
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following StateError was thrown during a scheduler callback:
Bad state: PictureRecorder is not recording

When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
lib/_engine/engine/canvaskit/picture_recorder.dart 31:7                       endRecording
lib/_engine/engine/canvaskit/embedded_views.dart 358:35                       submitFrame
lib/_engine/engine/canvaskit/rasterizer.dart 36:33                            draw
lib/_engine/engine/platform_dispatcher.dart 577:7                             render
lib/ui/src/ui/window.dart 93:50                                               render
packages/flutter/src/rendering/view.dart 229:15                               compositeFrame
packages/flutter/src/rendering/binding.dart 457:18                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 319:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1143:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1080:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1003:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 157:5                             invokeOnDrawFrame
lib/_engine/engine.dart 440:45                                                <fn>
====================================================================================================
```

**Flutter information**

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
[✓] VS Code (version 1.61.1)
[✓] Connected device (2 available)

**Device (please complete the following information):**
 - Device: Chrome Version 94.0.4606.81 (Official Build) (x86_64)
 - OS: mac OS Version 11.6

**Notes:**

The line `<script src="https://cdn.jsdelivr.net/npm/jsqr@1.3.1/dist/jsQR.min.js"></script>` was added to `web/index.html`

Note that  the alpha version `^1.0.0-alpha.1` does not compile.

`https://cozmo.github.io/jsQR/`works.

**Comment by C-8** [comment]
I have the same problem in webview. 
This seems to be a result of changes made in the flutter framework as described here: https://flutter.dev/docs/release/breaking-changes/platform-views-using-html-slots-web

**Comment by C-8** [comment]
I do have the same problem as you do. 
The warnings can be fixed by following the flutter integration guide: https://flutter.dev/docs/release/breaking-changes/platform-views-using-html-slots-web in qr_code_scanner/lib/src/web/flutter_qr_web.dart
However this does not solve the exception caught below the warnings..

**Comment by bverhagen** [comment]
I have the same problem as you describe (it is still there in `0.6.1`). It seems to have something to do with the CanvasKit renderer.

As a workaround, you can force Flutter to always use the html renderer rather than canvaskit by adding `--web-renderer html` to your `flutter build` and/or `flutter run`

**Comment by i3games** [comment]
> --web-renderer

cannot confirm that it works with html renderer, I get 

```
TypeError: dart.global.jsQR is not a function
    at flutter_qr_web._WebQrViewState.new._captureFrame2 (http://localhost:50249/packages/qr_code_scanner/src/web/flutter_qr_web.dart.lib.js:613:32)
    at _captureFrame2.next (<anonymous>)
    at runBody (http://localhost:50249/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:50249/dart_sdk.js:38690:7)
    at flutter_qr_web._WebQrViewState.new.[_captureFrame2]
    (http://localhost:50249/packages/qr_code_scanner/src/web/flutter_qr_web.dart.lib.js:598:20)
    at http://localhost:50249/packages/qr_code_scanner/src/web/flutter_qr_web.dart.lib.js:526:31
    at http://localhost:50249/dart_sdk.js:25467:9
```

**Comment by C-8** [comment]
> As a workaround, you can force Flutter to always use the html renderer rather than canvaskit by adding `--web-renderer html` to your `flutter build` and/or `flutter run`

This actually work for my purposes. It seems that the overlay is not supported with the html renderer though.

**Comment by juliansteenbakker** [comment]
For better web support, please see [mobile_scanner](https://pub.dev/packages/mobile_scanner). I will release a new version with web support later today.
