### ISSUE TITLE
[BUG] Crash on debug APK Android OS 11

### ISSUE THREAD

**Issue by dhirajhimani** [juliuscanute/qr_code_scanner#464]
While opening qr code scanner in debug apk , it is crashing have tested in android OS 11

Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ViewTreeViewModelStoreOwner"
 
`  
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewTreeViewModelStoreOwner;
at androidx.appcompat.app.AppCompatActivity.initViewTreeOwners(AppCompatActivity.java:220)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:194)
at de.jodamob.android.autolayout.AutoLayoutActivity.onCreate(AutoLayoutActivity.java:12)
at com.*.shared.inject.base.InjectedActivity.onCreate(InjectedActivity.kt:42)
at com.*.startup.StartupActivity.onCreate(StartupActivity.kt:72)
at android.app.Activity.performCreate(Activity.java:8198)
at android.app.Activity.performCreate(Activity.java:8182)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8506)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) `

**Comment by juliansteenbakker** [comment]
Can you please try using the latest version 0.7.0 and try again. Also checkout the new package [mobile_scanner](https://pub.dev/packages/mobile_scanner).
