### ISSUE TITLE
[BUG] Field '_channel@892294394' has not been initialized.

### ISSUE THREAD

**Issue by hdtuan87** [juliuscanute/qr_code_scanner#575]
**Describe the bug**
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: LateInitializationError: Field '_channel@892294394' has not been initialized.
#0      _QRViewState._channel (package:qr_code_scanner/src/qr_code_scanner.dart)
#1      _QRViewState.updateDimensions (package:qr_code_scanner/src/qr_code_scanner.dart:91:57)
#2      LifecycleEventHandler.didChangeAppLifecycleState (package:qr_code_scanner/src/lifecycle_event_handler.dart:15:29)
#3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:703:16)
#4      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:250:5)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77:49)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:47)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380:35)
#8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377:46)
#9      _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#10     _rootRun (dart:async/zone.dart:1426:13)
#11     _CustomZone.run (dart:async/zone.dart:1328:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#13     _invoke2 (dart:ui/hooks.dart:189:10)
#14     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#15     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#16     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#17     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589:22)
#18     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)

**Flutter information**
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale
    en-VN)
    • Flutter version 3.0.5 at /Users/dolphinmobileno1/Documents/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Device (please complete the following information):**
 - Device: iPhoneXS
 - OS: 15.5

**Screenshots**

**Additional context**
Show scan QRCode

**Comment by mciekurs2** [comment]
I'm having the same problem. Got report from crashlytics.

**Flutter information**

    • Flutter version 3.0.5 at /home/mc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Device**

- Device: Galaxy A12
- OS: Android 11

**Comment by AmjadAldya** [comment]
I'm having the same problem

**Comment by Frank3K** [comment]
We also faced this issue and provided a PR with a fix: https://github.com/juliuscanute/qr_code_scanner/pull/696.
