### ISSUE TITLE
Libs Stay in background camera seem no stop

### ISSUE THREAD

**Issue by massimilianochiodi** [juliuscanute/qr_code_scanner#586]
It seems that somehow the library remains suspended in the background despite using stopcamera and dispose
When route to other widget camera send 'updateAcquireFence: Did not find frame' endlessly

[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5.1 21G83 darwin-x64, locale it-IT)
    • Flutter version 3.3.0 on channel stable at /Users/massimiliano/developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffccd96b62 (7 days ago), 2022-08-29 17:28:57 -0700
    • Engine revision 5e9e0e0aa8
    • Dart version 2.18.0
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/massimiliano/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.5.1 21G83 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Device (please complete the following information):**
 - Device: Samsung A32, Android 12

**Comment by tehsunnliu** [comment]
Same problem. The camera doesn't start till I switch to the Front camera and then the Back camera.
Everytime I start the widget I get `updateAcquireFence: Did not find frame.`

**Comment by massimilianochiodi** [comment]
Ok use other plugin.
I have seen that the problem is the same, 
probably it is the android library that is used that is not updated or does not hook the context (UI View)

**Comment by tehsunnliu** [comment]
Hi, thank you for your response @massimilianochiodi. I was able to get it working by adding 
```dart
controller.pauseCamera();
controller.resumeCamera();
```
just after setting the scannedDataStream listener.

**Comment by massimilianochiodi** [comment]
E/flutter (11077): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(404, No barcode view found)
E/flutter (11077): #0      QRViewController.pauseCamera (package:qr_code_scanner/src/qr_code_scanner.dart:286:7)
E/flutter (11077): <asynchronous suspension>
E/flutter (11077): 
E/flutter (11077): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CameraException(404, No barcode view found)
E/flutter (11077): #0      QRViewController.stopCamera (package:qr_code_scanner/src/qr_code_scanner.dart:295:7)
E/flutter (11077): <asynchronous suspension>
E/flutter (11077):
