### ISSUE TITLE
crash on profile & release mode

### ISSUE THREAD

**Issue by AkashiWen** [juliuscanute/qr_code_scanner#617]
[GETX] GOING TO ROUTE /Scan
[GETX] Instance "MyScanController" has been created
[GETX] Instance "MyScanController" has been initialized
I/flutter (30301): type 'StackParentData' is not a subtype of type 'FlexParentData' in type cast
I/flutter (30301): #0      Flexible.applyParentData (package:flutter/src/widgets/basic.dart:5030)
I/flutter (30301): #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6061)
I/flutter (30301): #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:6082)
I/flutter (30301): #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5751)
I/flutter (30301): #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6299)
I/flutter (30301): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
I/flutter (30301): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
I/flutter (30301): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #26     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435)
I/flutter (30301): #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447)
I/flutter (30301): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #53     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435)
I/flutter (30301): #54     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447)
I/flutter (30301): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #64     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
I/flutter (30301): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
I/flutter (30301): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
I/flutter (30301): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
I/flutter (30301): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #86     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050)
I/flutter (30301): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041)
I/flutter (30301): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #93     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6300)
I/flutter (30301): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863)
I/flutter (30301): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3592)
I/flutter (30301): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904)
I/flutter (30301): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:4604)
I/flutter (30301): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859)
I/flutter (30301): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853)
I/flutter (30301): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (30301): Another exception was thrown: Instance of 'ErrorSummary'
I/flutter (30301): Another exception was thrown: Instance of 'ErrorSummary'
W/WM-WorkSpec(30301): Interval duration lesser than minimum allowed value; Changed to 900000
I/WM-WorkerWrapper(30301): Worker result SUCCESS for Work [ id=f03869bc-45fc-4090-8b5f-58100e4273e0, tags={ com.gyf.cactus.workmanager.CactusWorker } ]

######## -------- End ----------
The whole page was covered shows nothing. fine in debug mode.

1.0.1

flutter: 3.3.2

**Comment by AkashiWen** [comment]
found solution:
```dart
Expanded( // remove this
            child: _buildScanView(context),
          ),
```
