### ISSUE TITLE
[BUG] PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

### ISSUE THREAD

**Issue by SangwonJin** [juliuscanute/qr_code_scanner#633]
**Describe the bug**

PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference

**Flutter information**
Always provide the output of `flutter doctor -v` as it is needed in order to know on which Flutter versions the bug exists in.

**Device (please complete the following information):**
 - OS: [e.g. iOS8.1] android13

**Screenshots**

**Additional context**

**Comment by LiangShaing** [comment]
I have same problem. 
Device: Xiaomi Mi 10
OS:  android12
flutter : 2.10.5

**Comment by MokaCubrew** [comment]
I'm experiencing the same problem.

```shell
I/org.webrtc.Logging( 1166): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 1166): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
E/MethodChannel#flutter/platform_views( 1166): Failed to handle method call
E/MethodChannel#flutter/platform_views( 1166): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:570)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.View.<init>(View.java:5493)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.View.<init>(View.java:5638)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:704)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:700)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:696)
E/MethodChannel#flutter/platform_views( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:692)
E/MethodChannel#flutter/platform_views( 1166): 	at com.journeyapps.barcodescanner.CameraPreview.<init>(CameraPreview.java:228)
E/MethodChannel#flutter/platform_views( 1166): 	at com.journeyapps.barcodescanner.BarcodeView.<init>(BarcodeView.java:76)
E/MethodChannel#flutter/platform_views( 1166): 	at net.touchcapture.qr.flutterqr.CustomFramingRectBarcodeView.<init>(CustomFramingRectBarcodeView.kt:12)
E/MethodChannel#flutter/platform_views( 1166): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView.kt:117)
E/MethodChannel#flutter/platform_views( 1166): 	at net.touchcapture.qr.flutterqr.QRView.getView(QRView.kt:70)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:513)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:191)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#flutter/platform_views( 1166): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 1166): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter/platform_views( 1166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 1166): 	at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#flutter/platform_views( 1166): 	at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#flutter/platform_views( 1166): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#flutter/platform_views( 1166): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 1166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#flutter/platform_views( 1166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
I/flutter ( 1166): ----------------FIREBASE CRASHLYTICS----------------
I/flutter ( 1166): PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
I/flutter ( 1166): 	at android.view.ViewConfiguration.get(ViewConfiguration.java:570)
I/flutter ( 1166): 	at android.view.View.<init>(View.java:5493)
I/flutter ( 1166): 	at android.view.View.<init>(View.java:5638)
I/flutter ( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:704)
I/flutter ( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:700)
I/flutter ( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:696)
I/flutter ( 1166): 	at android.view.ViewGroup.<init>(ViewGroup.java:692)
I/flutter ( 1166): 	at com.journeyapps.barcodescanner.CameraPreview.<init>(CameraPreview.java:228)
I/flutter ( 1166): 	at com.journeyapps.barcodescanner.BarcodeView.<init>(BarcodeView.java:76)
I/flutter ( 1166): 	at net.touchcapture.qr.flutterqr.CustomFramingRectBarcodeView.<init>(CustomFramingRectBarcodeView.kt:12)
I/flutter ( 1166): 	at net.touchcapture.qr.flutterqr.QRView.initBarCodeView(QRView
I/flutter ( 1166): #0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
I/flutter ( 1166): #1      MethodChannel._invokeMethod
platform_channel.dart:310
I/flutter ( 1166): <asynchronous suspension>
I/flutter ( 1166): #2      TextureAndroidViewController._sendCreateMessage
platform_views.dart:1100
I/flutter ( 1166): <asynchronous suspension>
I/flutter ( 1166): #3      AndroidViewController.create
platform_views.dart:763
I/flutter ( 1166): <asynchronous suspension>
I/flutter ( 1166): #4      AndroidViewController.setSize
platform_views.dart:790
I/flutter ( 1166): <asynchronous suspension>
I/flutter ( 1166): #5      RenderAndroidView._sizePlatformView
platform_view.dart:175
I/flutter ( 1166): <asynchronous suspension>
I/flutter ( 1166): ----------------------------------------------------
```

**Flutter information**
```shell
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on Arch Linux 6.5.8-arch1-1, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] Connected device (3 available)
[✓] Network resources
```
**Device**
Galaxy Z Flip 5
Android 13

**qr_code_scanner**
1.0.1

**Comment by fr-vincentdelmundo** [comment]
encountering this as well, are there any updates for this bug?

**Comment by vavdiyaharesh** [comment]
still same issue exist, Any solution for this?

**Comment by ZephHe** [comment]
+1
