### ISSUE TITLE
[BUG] scan is error

### ISSUE THREAD

**Issue by bxxasn** [juliuscanute/qr_code_scanner#647]
qr_code_scanner:1.0.1
phone version:6.0
 
-----------------------Error----------------------
E  FATAL EXCEPTION: DecoderThread
                                                                                                    Process: com.acupayth, PID: 18409
                                                                                                    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:624)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
                                                                                                    	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
                                                                                                    	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
                                                                                                    	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
                                                                                                    	at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
                                                                                                    	at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
                                                                                                    	at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
                                                                                                    	at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loop(Looper.java:207)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=w-n0jUrUtPI&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=10 https://www.youtube.com/watch?v=QpnVENc9dIA&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=11

**Comment by crushman1** [comment]
Having same issue.

**Comment by miaozhenkun** [comment]
Having same issue.
