### ISSUE TITLE
java.lang.RuntimeException: startPreview failed [BUG] 

### ISSUE THREAD

**Issue by glauco111** [juliuscanute/qr_code_scanner#660]
**Describe the bug**
I'm using version 0.7.0 and sporadically I'm having this error... when it returns this message it gets a black screen, as soon as I apply the hot reload it works again...

**Flutter information**
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [versÃ£o 10.0.22621.1413], locale pt-BR)
    • Flutter version 2.10.5 at C:\Users\Glauco\fvm\default
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (12 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\Glauco\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.77.1)
    • VS Code at C:\Users\Glauco\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [versÃ£o 10.0.22621.1413]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.49
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.62

[√] HTTP Host Availability
    • All required HTTP hosts are available
**Device (please complete the following information):**
 - Device: Samsung S20 Fe
 - OS: Android 13

**Comment by glauco111** [comment]
D/CameraInstance(11338): Starting preview
E/CameraInstance(11338): Failed to start preview
E/CameraInstance(11338): java.lang.RuntimeException: startPreview failed
E/CameraInstance(11338): 	at android.hardware.Camera.startPreview(Native Method)
E/CameraInstance(11338): 	at com.journeyapps.barcodescanner.camera.CameraManager.startPreview(CameraManager.java:184)
