### ISSUE TITLE
[BUG] REOPEN #514

### ISSUE THREAD

**Issue by fauzipadlaw** [juliuscanute/qr_code_scanner#703]
I read thread on this issue #514, the issue is closed but the solution seems not right for this issue. It leads to another issue, crashing when opening app on Samsung Tab, in my case is Samsung Tab A8 and someone in the thread also mentioned the same behavior on Samsung Tab8+ after implementing the solution given. 

Based on the reason above, the issue is worth reopen to discuss further, hoping there is a right solution for this.

this is logs from firebase crashlytics:
```
Fatal Exception: java.lang.NoSuchMethodError: No interface method addWindowLayoutInfoListener(Landroid/app/Activity;Lj$/util/function/Consumer;)V in class Landroidx/window/extensions/layout/WindowLayoutComponent; or its super classes (declaration of 'androidx.window.extensions.layout.WindowLayoutComponent' appears in /system_ext/framework/androidx.window.extensions.jar)
       at androidx.window.layout.ExtensionWindowLayoutInfoBackend.registerLayoutChangeCallback(ExtensionWindowLayoutInfoBackend.kt:68)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invokeSuspend(WindowInfoTrackerImpl.kt:52)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(WindowInfoTrackerImpl.kt:2)
       at androidx.window.layout.WindowInfoTrackerImpl$windowLayoutInfo$1.invoke(WindowInfoTrackerImpl.kt:1)
       at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
       at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
       at androidx.window.java.layout.WindowInfoTrackerCallbackAdapter$addListener$1$1.invokeSuspend(WindowInfoTrackerCallbackAdapter.kt:96)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Thanks!

**Comment by fauzipadlaw** [comment]
I fixed the issue with this solution: https://stackoverflow.com/questions/74163927/flutter-chrash-in-android-12l-with-no-interface-method-addwindowlayoutinfoliste/74257036#74257036
