### ISSUE TITLE
Hot Reload causes an error

### ISSUE THREAD

**Issue by SeifKaroui** [juliuscanute/qr_code_scanner#76]
After a hot reload the QRView becomes blank and the following error appears:
(Note: i'm using an android emulator)

Exception has occurred.
PlatformException (PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
, null))

**Comment by artofbeinghuman** [comment]
Facing the same issue. It seems like the QRView wasn't properly disposed on disposing the containing route, as the scanning is still ongoing, even though the route was already popped.

**Comment by AndrsDev** [comment]
This error is happening to me too. It also happens with google_maps_flutter plugin. Maybe it is a flutter bug with embedding views
