### ISSUE TITLE
[android] ArithmeticException Crash

### ISSUE THREAD

**Issue by LeonDevLifeLog** [juliuscanute/qr_code_scanner#8]
```
java.lang.ArithmeticException: divide by zero
E/AndroidRuntime(27427): 	at com.journeyapps.barcodescanner.CameraPreview.calculateFrames(CameraPreview.java:389)
E/AndroidRuntime(27427): 	at com.journeyapps.barcodescanner.CameraPreview.previewSized(CameraPreview.java:461)
E/AndroidRuntime(27427): 	at com.journeyapps.barcodescanner.CameraPreview.access$300(CameraPreview.java:59)
E/AndroidRuntime(27427): 	at com.journeyapps.barcodescanner.CameraPreview$3.handleMessage(CameraPreview.java:199)
E/AndroidRuntime(27427): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(27427): 	at android.os.Looper.loop(Looper.java:207)
E/AndroidRuntime(27427): 	at android.app.ActivityThread.main(ActivityThread.java:7539)
E/AndroidRuntime(27427): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27427): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime(27427): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
sometime occur.
due to upstream library 
journeyapps/zxing-android-embedded#334
journeyapps/zxing-android-embedded#463

**Comment by dspicher** [comment]
This should be fixed now as zxing was bumped to 4.0.2.
